### ISSUE TITLE
Question about drag-and-drop styling

### ISSUE THREAD

**Issue by doug-shontz** [ticlo/rc-dock#100]
First off, thank you for an amazing library.  This is actually one of my favorite finds on GitHub!

I am working on a project where I am using the dock and my project has some very specific styling requirements.  I have been able to override and do everything I need except for one thing...the window dragging and dropping experience.

I need to create light and dark themes for the application and, when dragging windows around, the arrows are defaulting to grey on a white background and the box background color during the dragging is a shade of blue with what I'm guessing is some opacity.

I've looked through the library as best I can and cannot find how I could style the arrows and change the background color of the dragging experience from a blue to anything else.  Is this possible, and, if not currently, I would be happy to work on a PR if you could point me in the right direction.

Thanks for your time!

**Comment by doug-shontz** [comment]
I was able to figure it out.  Putting this here in case anyone else needs it.  I used the event listener breakpoints for mousedown to freeze the inspector and then drill through the elements to find the things I needed.  Here are the two CSS classes I needed to override:

```css
/* This CSS for the drag layer...the background */

.dock-layout > .dock-drop-indicator {
    background: orange;
    opacity: 0.15;
}

/* This CSS for the arrows */

.dock-drop-layer .dock-drop-square {
    background: black;
}

.dock-drop-layer .dock-drop-square:hover {
    background: orange;
}

```
