### ISSUE TITLE
Allow float boxes to go outside the layout DOM

### ISSUE THREAD

**Issue by adityatoshniwal** [ticlo/rc-dock#130]
Hi @rinick,
![Screenshot 2021-11-02 at 23 00 48](https://user-images.githubusercontent.com/31855755/140895338-76949220-7b15-43d2-a357-3f7b4cbe8b72.png)

I have a requirement where there is a fixed toolbar on the top and a status bar at the bottom. Now, I'm using the layout in middle. But the problem is, the floating boxes are not allowed to go beyond layout edge.
I was wondering if there is anything which can be done with existing API.

**Comment by adityatoshniwal** [comment]
If we move the dock-box dock-fbox out of dock-layout in the DOM (using inspect element) then it works.

**Comment by rinick** [comment]
what if you just add this css
```css
.dock-layout > .dock-hbox, .dock-layout > .dock-vbox  {
    height: calc(100% - 100px);
   top: 100px;
}
```
